In [1]:
# advance numpy
import numpy as np
a= np.array([1,2,3])
b=np.array([3,4,5])
print(type(a))
print(a.shape)
print(type(b))
print(b)



<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
[3 4 5]


In [3]:
a[0]=5
print(a)
b= np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

[5 2 3]
(2, 3)
1 2 4


In [8]:
#create an array of all zeros and array of all ones
import numpy as np
a=np.zeros([2,2])
print(a)

b=np.ones((1,2))
print(b)
#ceate an array with constants first rows sec columb and 3rd value
c=np.full((2,2),7)
print(c)

d=np.eye(2)
print(d)

e=np.random.random((2,2))
print(e)

#

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.02969626 0.01827067]
 [0.32098671 0.4848108 ]]


In [9]:
#numpy linspace
import numpy as np
np.linspace(2.0,3.0,num=5)
array([2. , 2.25, 2.75, 3.])
np.linspace(2.0,3.0,num=5,endpoint=false)
array([2.,2.2,2.4,2.6,2.8])

NameError: name 'array' is not defined

In [12]:
#slicing 
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

b=a[:2,1:3]
print(a[0,1])
print(a[:,:])
print(a[:2,1:3])
print(a[0:2,1:2])
print(a[2:3,0:2])
print(a[:2,1:])
print(a[-2:-1,-2:1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[[2]
 [5]]
[[7 8]]
[[2 3]
 [5 6]]
[]


In [13]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2],[0,1,0]])
print(np.array([a[0,0],a[1,1],a[2,1]]))
print

[1 4 5]
[1 4 6]


In [14]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
b=np.array([0,2,0,1])


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
#bool
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
bool_idx = (a>2)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [16]:
import numpy as np
x=np.array([1,2])
print(x.dtype)
y=np.array([1,2],dtype=np.int64)
print(y.dtype)


int32
int64


In [20]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))
print(np.divide(x,y))
print(np.sqrt(x))
print(x.T)
v=np.array([1,2,3])
print(v)
print(v.T)

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [21]:
import numpy as np
arr = np.arange(16)
print("The Original Array is:\n",arr)
arr1 = np.arange(16).reshape(2,8)
print("The Reshaped array is:\n",arr1)

The Original Array is:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
The Reshaped array is:
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [22]:
import numpy as np

# Define a square matrix (2x2 in this case)
A = np.array([[2, 1], [1, 1]])

# Compute eigenvalues and eigenvectors using np.linalg.eig
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: [2.61803399 0.38196601]
Eigenvectors: [[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]
